#: Name: Matthew Williams
#: Date: 20:Feb:2023
#: Config file for the Simple Demography simulation

## Input Parameters
simulation_model_name: "Model1_DTWF" # Identification name for the simulation.  
window_length_Fstats: "5000000" # The window length for jackknife of f-statistics. 
N_replicates: "5000" # Number of simulation iterations to perform.
DTWF_generations: "100" # Number of generations to simulate under the discrete time wright fisher model.
MRCA_split_generation: "200e3" # The number of years for the deepest split in the tree (T0)
N_diploid_samples: "20" # Number of diploid samples to take from each population. 
diploid_Ne: "10e3" # The effective population size for each population. 
generation_time: "29" # The generation time. 

#: Chromosomes Configuration
#: Source https://popsim-consortium.github.io/stdpopsim-docs/latest/catalog.html#sec_catalog_HomSap 
recombination_rate: None # Specified as None if simulating Chrs 1-2 stdpopsim values as specified in the manuscript. 
chromosome_length: None # Specified as None if simulating Chrs 1-2 stdpopsim values as specified in the manuscript.



## Scripts
# R
R_script_DIR: "src/r/"
ts_branch_FST_Summary_Output: "src/r/ts_branch_FST_Summary_Table.R"
ts_branch_F2_matrix: "src/r/ts_branch_F2_matrix.R"
ts_branch_qpAdmRotation: "src/r/ts_branch_qpAdmRotation_Model_Violation.R"
ts_branch_qpAdmRotation_SummaryTable: "src/r/ts_branch_qpAdmRotation_Model_Violation_SummaryTable.R"
ts_branch_admixF3: "src/r/ts_branch_admixF3.R"
ts_branch_admixF3_SummaryTable: "src/r/ts_branch_admixF3_SummaryTable.R"
ts_branch_qpAdmRotation_SummaryTable_2source: "src/r/ts_branch_qpAdmRotation_2sources_SummaryTable.R"
ts_branch_qpAdmRotation_2source: "src/r/ts_branch_qpAdmRotation_2sources.R"

# python
msp_ts_simulate: "src/python/msp_simulate_ts_dtwf_model1.py"
ts_branch_FST: "src/python/msp_branch_FST.py"
ts_branch_F2: "src/python/msp_branch_F2.py"

###################
## ******* 
# SOFTWARE PACKAGES
## * R packages required
# tidyverse
# optparse
# data.table
# admixtools
## * Python packages required
# msprime 1.2.0
# pandas 1.3.5
# tabulate
# argparse  1.1
# random
# numpy 1.23.1
# tskit 0.5.3
# math
