__default__:
  account: "cdh5313_b"
  partition: "burst"
  qos: "burst4x"
  cpus: "{threads}"
  time: 0:45:00
  mem: "64G"
  output: "logs_slurm/{rule}.{wildcards}.out"
  email: "mkw5910@psu.edu"
  email_type: "FAIL"


msp_ts_simulate:
  partition: "burst"
  qos: "burst4x"
  mem: '20G'
  time: "337:00:00"
  threads: '1'

ts_branch_FST_DT:
  partition: "burst"
  qos: "burst4x"
  mem: '25G'
  time: "47:10:00"
  threads: '1'

ts_branch_FST_Summary_Output:
  partition: "burst"
  qos: "burst4x"
  mem: '4G'
  time: "00:90:00"
  threads: '1'

ts_branch_F2_DT:
  partition: "burst"
  qos: "burst4x"
  mem: '30G'
  time: "47:20:00"
  threads: '1'

ts_branch_F2_matrix:
  partition: "burst"
  qos: "burst4x"
  mem: '25G'
  time: "47:30:00"
  threads: '1'

ts_branch_qpAdmRotation:
  partition: "burst"
  qos: "burst4x"
  mem: '8G'
  time: "24:00:00"
  threads: '1'

ts_branch_qpAdmRotation_Summary_Output:
  partition: "burst"
  qos: "burst4x"
  mem: '8GB'
  time: "00:90:00"
  threads: '1'

ts_branch_qpAdmReplacement:
  partition: "burst"
  qos: "burst4x"
  mem: '8G'
  time: "24:50:00"
  threads: '1'

ts_branch_qpAdmReplacement_Summary_Output:
  partition: "burst"
  qos: "burst4x"
  mem: '4GB'
  time: "00:90:00"
  threads: '1'

ts_branch_admixtureF3:
  partition: "burst"
  qos: "burst4x"
  mem: '25G'
  time: "24:60:00"
  threads: '1'

ts_branch_admixtureF3_Summary_Output:
  partition: "burst"
  qos: "burst4x"
  mem: '4G'
  time: "00:90:00"
  threads: '1'

msp_ts_mutate:
  partition: "burst"
  qos: "burst4x"
  mem: '40G'
  time: "02:00:00"
  threads: '1'

ts_mu_eigenstrat:
  partition: "burst"
  qos: "burst4x"
  mem: '120G'
  time: "72:00:00"
  threads: '1'

ts_mu_eig_aDNA_processing:
  partition: "burst"
  qos: "burst4x"
  mem: '250G'
  time: "48:00:00"
  threads: '1'

ts_mu_eig_aDNA_qpAdmRotation:
  partition: "burst"
  qos: "burst4x"
  mem: '16G'
  time: "47:00:00"
  threads: '1'

ts_mu_eig_aDNA_qpAdmRotation_Summary_Output:
  partition: "burst"
  qos: "burst4x"
  mem: '4G'
  time: "00:90:00"
  threads: '1'

ts_mu_eig_aDNA_qpAdmReplacement:
  partition: "burst"
  qos: "burst4x"
  mem: '8G'
  time: "72:90:00"
  threads: '1'

ts_mu_eig_aDNA_qpAdmReplacement_Summary_Output:
  partition: "burst"
  qos: "burst4x"
  mem: '4G'
  time: "00:90:00"
  threads: '1'

ts_mu_eig_aDNA_admixtureF3:
  partition: "burst"
  qos: "burst4x"
  mem: '8G'
  time: "72:05:00"
  threads: '1'

ts_mu_eig_aDNA_admixtureF3_Summary_Output:
  partition: "burst"
  qos: "burst4x"
  mem: '4G'
  time: "00:90:00"
  threads: '1'

ts_mu_eig_aDNA_FST:
  partition: "burst"
  qos: "burst4x"
  mem: '32G'
  time: "72:05:00"
  threads: '1'

